// src/pages/blog.tsx
import React from 'react';
import Image from 'next/image';
import styled from 'styled-components';

import { Link } from '$components/Link';
import { Layout } from '$components/Layout';
import { getAllPosts } from '$lib/api';

const Grid = styled.div`
	@media screen and (min-width: 700px) {
		display: grid;
		grid-template-columns: 35% 65%;
		grid-gap: 2rem;
	}
`;

const Img = styled(Image)`
	height: auto;
	max-height: 25vh;
	width: 100%;

	@media screen and (min-width: 700px) {
		max-height: unset;
	}
`;

type BlogProps = {
	headshot: {
		url: string;
	};
	posts: {
		title: string;
		content: string;
		slug: string;
		coverPhoto: {
			url: string;
			height: number;
			width: number;
			blur: string;
		};
	}[];
};

const Blog = (props: BlogProps) => (
	<Layout
		title="A Boston based web developer specializing in performant web applications"
		imageUrl={props.headshot.url}
	>
		{props.posts.map(bp => (
			<Grid key={bp.slug}>
				<Img
					layout="responsive"
					src={bp.coverPhoto.url}
					height={bp.coverPhoto.height}
					width={bp.coverPhoto.width}
					blurDataURL={bp.coverPhoto.blur}
					placeholder="blur"
				/>
				<div>
					<Link to={`/${bp.slug}`}>
						<p>{bp.title}</p>
					</Link>
				</div>
			</Grid>
		))}
	</Layout>
);

export default Blog;

export async function getStaticProps() {
	const { headshot, posts } = await getAllPosts();

	return {
		props: {
			headshot,
			posts
		}
	};
}

// src/routes/blog/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import Image from '$lib/components/Image/Image.svelte';

	export let data: PageData;
</script>

<svelte:head>
	<title>Blog | Andrew Kiernan</title>
</svelte:head>

{#each data.posts as post}
	<div class="grid">
		<Image
			alt="blog-post-header"
			class="img"
			src={post.cover_photo.url}
			placeholder={post.cover_photo.blur}
		/>
		<div>
			<a href={`/blog/${post.slug}`}>
				<p>{post.title}</p>
			</a>
		</div>
	</div>
{/each}

<style>
	@media screen and (min-width: 700px) {
		.grid {
			display: grid;
			grid-template-columns: 35% 65%;
			grid-gap: 2rem;
		}

		.grid :global(.img) {
			max-height: unset;
		}
	}

	.grid :global(.img) {
		height: auto;
		max-height: 25vh;
		width: 100%;
	}
</style>
