// src/routes/[slug]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	export let data: PageData;

	console.log(data.post.content);
</script>

<h1>{data.post.title}</h1>
<img
	alt="blog-cover"
	src={data.post.coverPhoto.url}
	height={data.post.coverPhoto.height}
	width={data.post.coverPhoto.width}
/>
{@html data.post.content}

// src/app/blog/[slug]/page.tsx
import { fetchGraphQL } from '$lib/api';
import { transformImage } from '$lib/transformImage';
import { Post } from './post';

const BlogPost = async ({ params }) => {
	const { post } = await getData(params);

	return <Post post={post} />;
};

export default BlogPost;

async function getData(params) {
	const { data } = await fetchGraphQL(`
		query {
			post: blogPostCollection(where: { slug: "${params.slug}" }) {
				items {
					title
					content 
					coverPhoto {
						url
						height
						width
					}
				}

			}
		}
	`);
	const [post] = data.post.items;
	const image = await transformImage(post.coverPhoto);
	return {
		post: {
			...post,
			coverPhoto: image
		}
	};
}
