// src/lib/components/Navbar/Navbar.svelte
<script lang="ts">
	import Switch from './ThemeSwitcher.svelte';
	import { page } from '$app/stores';

	import logoLight from '$lib/img/logo.svg';
	import logoDark from '$lib/img/logo-inverted.svg';

	let theme: 'light' | 'dark' = 'light';
</script>

<nav class="nav">
	<div class="nav-brand">
		<a class="brand-link" href="/" aria-label="my logo">
			{#if theme === 'light'}
				{logoLight}
			{:else}
				{logoDark}
			{/if}
		</a>
	</div>
	<div class="site-theme-toggle">
		<Switch {theme} />
	</div>
	<div>
		<a class="nav-link" class:active={$page.url.pathname.startsWith('/blog')} href="/blog">
			Blog
		</a>
		<a class="nav-link" class:active={$page.url.pathname.startsWith('/projects')} href="/projects">
			Projects
		</a>
		<a class="nav-link" class:active={$page.url.pathname.startsWith('/resume')} href="/resume">
			Resume
		</a>
		<a class="nav-link" class:active={$page.url.pathname.startsWith('/contact')} href="/contact">
			Contact
		</a>
	</div>
</nav>

<style>
	.nav {
		align-items: center;
		display: flex;
		height: 3rem;
		justify-content: space-between;
	}

	.nav-brand {
		display: flex;
		height: 100%;
	}

	.site-theme-toggle {
		flex: 1;
	}

	.brand-link {
		display: flex;
		height: 100%;
		padding: 0.5rem;
	}

	.nav-link {
		text-decoration: none;
		font-size: 0.875rem;
		border-bottom: 0.3rem solid transparent;
		color: var(--text-color);
		padding: 1rem;
		padding-bottom: 0.4rem;
	}

	.active {
		border-bottom-color: var(--primary-color);
	}

	@media screen and (min-width: 500px) {
		.nav-link {
			font-size: 1rem;
			padding: 1.5rem;
			padding-bottom: 0.6rem;
		}
	}

	@media screen and (min-width: 768px) {
		.nav {
			height: 5rem;
			padding: 0 4rem;
		}

		.nav-link {
			font-size: 1.125rem;
		}
	}
</style>

// src/components/Navbar.tsx
import React from 'react';
import styled from 'styled-components';
import SVG from 'react-inlinesvg';

import { Link } from './Link';
import { SiteTheme, useSiteTheme } from '../hooks/useSiteTheme';
import logoLight from '../img/logo.svg';
import logoDark from '../img/logo-inverted.svg';
import lightIcon from '../img/light-mode-icon.svg';
import darkIcon from '../img/dark-mode-icon.svg';

const Nav = styled.nav`
  align-items: center;
  border-bottom: 1px solid #ccc;
  display: flex;
  height: 3rem;
  justify-content: space-between;

  @media screen and (min-width: ${props => props.theme.breakpoints.medium}) {
    height: 5rem;
    padding: 0 2rem;
  }
`;

const NavBrand = styled.div`
  display: flex;
  height: 100%;
`;

const SiteThemeToggle = styled.div`
  flex: 1;
`;

const BrandLink = styled(Link)`
  display: flex;
  height: 100%;
  padding: 0.5rem;
`;

const BrandLogo = styled(SVG)`
  height: 100%;
  width: auto;
`;

const NavLink = styled(Link)`
  text-decoration: none;
  font-size: 0.9rem;
  border-bottom: 0.3rem solid transparent;
  color: var(--text-color);
  padding: 1.5rem;
  padding-bottom: 0.6rem;

  &.active {
    border-bottom-color: var(--primary-color);
  }

  &::visited: {
    color: var(--text-color);
  }

  @media screen and (min-width: ${props => props.theme.breakpoints.medium}) {
    font-size: 1.25rem;
    padding: 2rem;
    padding-bottom: 1.45rem;
  }
`;

const SwitchContainer = styled.div`
  align-items: center;
  display: flex;
  height: 100%;
  width: auto;
`;
const SwitchIcon = styled(SVG)`
  border-radius: 2rem;
  height: 2rem;
  width: 2rem;
  fill: var(--text-color);
`;

type Props = {
  siteTheme: SiteTheme;
  setSiteTheme: (_st: SiteTheme) => void;
};

const Switch = (p: Props) => {
  // @ts-ignore
  const icon: string = p.siteTheme === 'light' ? lightIcon.src : darkIcon.src;
  return (
    <label htmlFor="site-theme">
      <SwitchContainer>
        <SwitchIcon src={icon} />
      </SwitchContainer>
      <input
        id="site-theme"
        type="checkbox"
        hidden
        checked={p.siteTheme === 'dark'}
        onChange={() => {
          p.setSiteTheme(p.siteTheme === 'light' ? 'dark' : 'light');
        }}
      />
    </label>
  );
};

const Navbar = () => {
  const [theme, setTheme] = useSiteTheme();
  return (
    <Nav>
      <NavBrand>
        <BrandLink to="/">
          {/* @ts-ignore */}
          <BrandLogo src={theme === 'light' ? logoLight.src : logoDark.src} />
        </BrandLink>
      </NavBrand>
      <SiteThemeToggle>
        <Switch siteTheme={theme} setSiteTheme={setTheme} />
      </SiteThemeToggle>
      <div>
        <NavLink to="/blog">Blog</NavLink>
        <NavLink to="/projects">Projects</NavLink>
        <NavLink to="/resume">Resume</NavLink>
        <NavLink to="/contact">Contact</NavLink>
      </div>
    </Nav>
  );
};

export default Navbar;
