// src/routes/blog/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import Image from '$lib/components/Image/Image.svelte';

	export let data: PageData;
</script>

<svelte:head>
	<title>Blog | Andrew Kiernan</title>
</svelte:head>

{#each data.posts as post}
	<div class="grid">
		<Image
			alt="blog-post-header"
			class="img"
			src={post.cover_photo.url}
			placeholder={post.cover_photo.blur}
		/>
		<div>
			<a href={`/blog/${post.slug}`}>
				<p>{post.title}</p>
			</a>
		</div>
	</div>
{/each}

<style>
	@media screen and (min-width: 700px) {
		.grid {
			display: grid;
			grid-template-columns: 35% 65%;
			grid-gap: 2rem;
		}

		.grid :global(.img) {
			max-height: unset;
		}
	}

	.grid :global(.img) {
		height: auto;
		max-height: 25vh;
		width: 100%;
	}
</style>

// src/app/blog/page.tsx
import Image from 'next/image';

import { Link } from '$components/Link';
import { getAllPosts } from '$lib/api';
import styles from './blog.module.css';

const Blog = async () => {
	const { posts } = await getData();
	return (
		<>
			{posts.map(bp => (
				<div className={styles.grid} key={bp.slug}>
					<Image
						alt="blog-post-header"
						className={styles.img}
						src={bp.coverPhoto.url}
						height={bp.coverPhoto.height}
						width={bp.coverPhoto.width}
						blurDataURL={bp.coverPhoto.blur}
						placeholder="blur"
					/>
					<div>
						<Link to={`/blog/${bp.slug}`}>
							<p>{bp.title}</p>
						</Link>
					</div>
				</div>
			))}
		</>
	);
};

export default Blog;

async function getData() {
	const { posts } = await getAllPosts();

	return {
		posts
	};
}
